//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeylonBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTag
    {
        public int ArticleTagID { get; set; }
        public int ArticleID { get; set; }
        public int TagID { get; set; }
        public int Active { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
