//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeylonBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleCategories = new HashSet<ArticleCategory>();
            this.ArticleReplies = new HashSet<ArticleReply>();
            this.ArticleTags = new HashSet<ArticleTag>();
        }
    
        public int ArticleID { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleContent { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int SortID { get; set; }
        public int IsTop { get; set; }
        public int Active { get; set; }
        public Nullable<int> ReadNum { get; set; }
    
        public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
        public virtual ICollection<ArticleReply> ArticleReplies { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
    }
}
