//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleReply
    {
        public ArticleReply()
        {
            this.ArticleReply11 = new HashSet<ArticleReply>();
        }
    
        public int ArticleReplyID { get; set; }
        public string ReplyContent { get; set; }
        public string ReplyUserName { get; set; }
        public string ReplyUserEmail { get; set; }
        public System.DateTime ReplyTime { get; set; }
        public int ArticleID { get; set; }
        public int ToReplyID { get; set; }
        public int Active { get; set; }
        public int UserID { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ArticleReply> ArticleReply11 { get; set; }
        public virtual ArticleReply ToReply { get; set; }
    }
}
