//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionID { get; set; }
        public string SectionTitle { get; set; }
        public string SectionContent { get; set; }
        public int SortID { get; set; }
        public string SectionCode { get; set; }
    }
}
